import "@/app/_styles/globals.css";
import dynamic from "next/dynamic";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { CustomerProvider } from "@/app/_context/CustomerContext";
const Footer = dynamic(() => import("@/app/_components/Footer"));

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-zinc-950 px-2 py-5`}>
        <Toaster
          position="top-center"
          reverseOrder={false}
          gutter={8}
          containerClassName=""
          containerStyle={{}}
          toastOptions={{
            duration: 5000,
            removeDelay: 1000,
            // style: {
            //   background: "#363636",
            //   color: "#fff",
            // },

            success: {
              className: "!text-zinc-100 !bg-zinc-800",
              duration: 3000,
              iconTheme: {
                primary: "var(--toast-icon-success-primary)",
                secondary: "var(--toast-icon-success-secondary)",
              },
            },

            loading: {
              className: "!text-zinc-100 !bg-zinc-800",
              duration: 7000,
              iconTheme: {
                primary: "var(--toast-icon-success-primary)",
                secondary: "var(--toast-icon-success-secondary)",
              },
            },
            error: {
              className: "!bg-red-600 !text-red-50",
              duration: 5000,
              iconTheme: {
                primary: "var(--toast-icon-error-primary)",
                secondary: "var(--toast-icon-error-secondary)",
              },
            },
          }}
        />
        <CustomerProvider>
          <main className="pb-10 sm:min-w-auto md:pb-0">
            {/* bottom padding = height of bottom nav */}
            {children}
            <Footer />
          </main>
        </CustomerProvider>
      </body>
    </html>
  );
}
